### ISSUE TITLE
What are the restrictions on picking pins for PWM and EN, if any?

### ISSUE THREAD

**Issue by crteensy** [AlkaMotors/AM32_G071#1]
I'd like to simplify routing of my ESC. To do that, I need to know the restrictions on picking PWM/EN pins.

**Comment by AlkaMotors** [comment]
The easiest if for the pwm pins to to be on the primary timer output channels. These would normally be the ones to the upper MOSFETs. This keeps all the logic the same. The enable pins can be any available pin that's easy for routing. 
Since dead time and advanced features aren't important you can pick the timer of choice for the PWM output . It doesn't have to be timer 1. This opens up more options .

**Comment by crteensy** [comment]
So any pin with TIMx_CHy alternate function can be used, where x = 1,2,3. Example:
![image](https://user-images.githubusercontent.com/7403405/106025840-71de0200-60c9-11eb-8fc9-44bbd3477e31.png)

TIM14,15,16,17 have less than 3 PWM channels so they can't be used.
Why is dead time not important?

**Comment by AlkaMotors** [comment]
Most pwm enable type bridges impose their own dead time or have a external resistor to set so dead time on the MCU is not so important, your setup may be different. Timer 1 has advanced motor control features for driving independent gates with automatic dead time insertion and complementary outputs. However all you  might need is a pwm signal ,so you don't have to use TIM 1. I am using timers 2(timing zero crosses), 3(input capture), 6(10khz interrupt), 14(timing delay), and 17(?) in the code.

**Comment by crteensy** [comment]
Then I'll keep it simple by only reordering PWM pins and picking EN to fit.
